export enum ProductStatus {
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  FINISHED = 'FINISHED',
  CANCELED_BY_RESTAURANT = 'CANCELED_BY_RESTAURANT',
  CANCELED_BY_CLIENT = 'CANCELED_BY_CLIENT'
}
